#!/usr/bin/env python3
"""
SMV model generator - converts CFG data to NuSMV format.
"""


class SMVGenerator:
    """Generates NuSMV models from control flow graph data."""

    def __init__(self):
        self.model_lines = []

    def generate(self, cfg_data, options):
        """
        Generate SMV model from CFG data.

        Args:
            cfg_data: Dictionary containing CFG information
            options: Generation options

        Returns:
            String containing complete SMV model
        """
        self.model_lines = []

        # Generate header
        self._generate_header()

        # Generate MODULE main
        self._generate_module_main(cfg_data, options)

        return '\n'.join(self.model_lines)

    def _generate_header(self):
        """Generate SMV file header with comments."""
        self.model_lines.extend([
            "-- SMV Model automatically extracted from source code",
            "-- Generated by smv-model-extractor",
            "",
        ])

    def _generate_module_main(self, cfg_data, options):
        """Generate the main MODULE."""
        self.model_lines.append("MODULE main")
        self.model_lines.append("")

        # VAR section
        self._generate_var_section(cfg_data)

        # ASSIGN section
        self._generate_assign_section(cfg_data)

        # DEFINE section (optional)
        self._generate_define_section(cfg_data)

    def _generate_var_section(self, cfg_data):
        """Generate VAR section with state variables."""
        self.model_lines.append("VAR")

        # Program counter / state variable
        states = cfg_data.get('states', [])
        if states:
            state_ids = [s['id'] for s in states]
            self.model_lines.append(f"  pc : {{{', '.join(state_ids)}}};")

        # Program variables
        variables = cfg_data.get('variables', set())
        for var in sorted(variables):
            # Abstract to boolean or small integer domain
            self.model_lines.append(f"  {var} : boolean;")

        self.model_lines.append("")

    def _generate_assign_section(self, cfg_data):
        """Generate ASSIGN section with initial values and transitions."""
        self.model_lines.append("ASSIGN")

        # Initial state
        initial_state = cfg_data.get('initial_state')
        if initial_state:
            self.model_lines.append(f"  init(pc) := {initial_state};")

        # State transitions
        self._generate_transitions(cfg_data)

        # Variable initialization
        variables = cfg_data.get('variables', set())
        for var in sorted(variables):
            self.model_lines.append(f"  init({var}) := FALSE;")

        self.model_lines.append("")

    def _generate_transitions(self, cfg_data):
        """Generate next-state transitions."""
        transitions = cfg_data.get('transitions', [])
        states = cfg_data.get('states', [])

        if not states:
            return

        # Build transition map
        trans_map = {}
        for trans in transitions:
            src = trans.get('from')
            if src not in trans_map:
                trans_map[src] = []
            trans_map[src].append(trans)

        # Generate next(pc) case statement
        self.model_lines.append("  next(pc) := case")

        for state in states:
            state_id = state['id']
            if state_id in trans_map:
                state_trans = trans_map[state_id]
                if len(state_trans) == 1:
                    # Single transition
                    trans = state_trans[0]
                    condition = trans.get('condition', 'TRUE')
                    target = trans.get('to')
                    self.model_lines.append(f"    pc = {state_id} & {condition} : {target};")
                else:
                    # Multiple transitions (branching)
                    for trans in state_trans:
                        condition = trans.get('condition', 'TRUE')
                        target = trans.get('to')
                        self.model_lines.append(f"    pc = {state_id} & {condition} : {target};")
            else:
                # No outgoing transitions (final state)
                self.model_lines.append(f"    pc = {state_id} : {state_id};")

        self.model_lines.append("    TRUE : pc;")
        self.model_lines.append("  esac;")
        self.model_lines.append("")

    def _generate_define_section(self, cfg_data):
        """Generate DEFINE section for derived properties."""
        # Optional: add derived properties or macros
        pass

    def generate_mapping_explanation(self, cfg_data):
        """
        Generate human-readable explanation of program-to-model mapping.

        Args:
            cfg_data: CFG data structure

        Returns:
            String containing mapping explanation
        """
        lines = []
        lines.append("=" * 70)
        lines.append("PROGRAM-TO-MODEL MAPPING EXPLANATION")
        lines.append("=" * 70)
        lines.append("")

        # States mapping
        lines.append("STATES:")
        lines.append("-" * 70)
        states = cfg_data.get('states', [])
        for state in states:
            state_id = state['id']
            label = state.get('label', 'unknown')
            state_type = state.get('type', 'normal')
            lines.append(f"  {state_id}: {label} ({state_type})")
        lines.append("")

        # Variables mapping
        lines.append("STATE VARIABLES:")
        lines.append("-" * 70)
        variables = cfg_data.get('variables', set())
        if variables:
            for var in sorted(variables):
                lines.append(f"  {var}: Abstracted to boolean domain")
        else:
            lines.append("  (No state variables tracked)")
        lines.append("")

        # Transitions mapping
        lines.append("TRANSITIONS:")
        lines.append("-" * 70)
        transitions = cfg_data.get('transitions', [])
        if transitions:
            for trans in transitions:
                src = trans.get('from', '?')
                dst = trans.get('to', '?')
                cond = trans.get('condition', 'TRUE')
                lines.append(f"  {src} -> {dst}  [condition: {cond}]")
        else:
            lines.append("  (No transitions defined)")
        lines.append("")

        # Functions analyzed
        lines.append("FUNCTIONS ANALYZED:")
        lines.append("-" * 70)
        functions = cfg_data.get('functions', [])
        for func in functions:
            func_name = func.get('name', 'unknown')
            lines.append(f"  - {func_name}")
        lines.append("")

        lines.append("=" * 70)

        return '\n'.join(lines)
