#!/bin/bash
# Auto-generated security scan commands for all skills
# Generated on $(date)

# Create output directory if it doesn't exist
mkdir -p _report

skill-security-scan scan skills/abstract-domain-explorer -o _report/abstract-domain-explorer
skill-security-scan scan skills/abstract-invariant-generator -o _report/abstract-invariant-generator
skill-security-scan scan skills/abstract-state-analyzer -o _report/abstract-state-analyzer
skill-security-scan scan skills/abstract-trace-summarizer -o _report/abstract-trace-summarizer
skill-security-scan scan skills/acsl-annotation-assistant -o _report/acsl-annotation-assistant
skill-security-scan scan skills/ambiguity-detector -o _report/ambiguity-detector
skill-security-scan scan skills/api-design-assistant -o _report/api-design-assistant
skill-security-scan scan skills/api-documentation-generator -o _report/api-documentation-generator
skill-security-scan scan skills/assertion-synthesizer -o _report/assertion-synthesizer
skill-security-scan scan skills/behavior-preservation-checker -o _report/behavior-preservation-checker
skill-security-scan scan skills/behavioral-mutation-analyzer -o _report/behavioral-mutation-analyzer
skill-security-scan scan skills/bisect-aware-instrumentation -o _report/bisect-aware-instrumentation
skill-security-scan scan skills/bug-history-summarizer -o _report/bug-history-summarizer
skill-security-scan scan skills/bug-localization -o _report/bug-localization
skill-security-scan scan skills/bug-reproduction-test-generator -o _report/bug-reproduction-test-generator
skill-security-scan scan skills/bug-to-patch-generator -o _report/bug-to-patch-generator
skill-security-scan scan skills/build-ci-migration-assistant -o _report/build-ci-migration-assistant
skill-security-scan scan skills/c-cpp-to-lean4-translator -o _report/c-cpp-to-lean4-translator
skill-security-scan scan skills/cd-pipeline-generator -o _report/cd-pipeline-generator
skill-security-scan scan skills/change-log-generator -o _report/change-log-generator
skill-security-scan scan skills/ci-pipeline-synthesizer -o _report/ci-pipeline-synthesizer
skill-security-scan scan skills/code-change-summarizer -o _report/code-change-summarizer
skill-security-scan scan skills/code-comment-generator -o _report/code-comment-generator
skill-security-scan scan skills/code-completion-semantic-constraints -o _report/code-completion-semantic-constraints
skill-security-scan scan skills/code-instrumentation-generator -o _report/code-instrumentation-generator
skill-security-scan scan skills/code-optimizer -o _report/code-optimizer
skill-security-scan scan skills/code-pattern-extractor -o _report/code-pattern-extractor
skill-security-scan scan skills/code-refactoring-assistant -o _report/code-refactoring-assistant
skill-security-scan scan skills/code-repair-generation-combo -o _report/code-repair-generation-combo
skill-security-scan scan skills/code-review-assistant -o _report/code-review-assistant
skill-security-scan scan skills/code-search-assistant -o _report/code-search-assistant
skill-security-scan scan skills/code-smell-detector -o _report/code-smell-detector
skill-security-scan scan skills/code-summarizer -o _report/code-summarizer
skill-security-scan scan skills/code-translation -o _report/code-translation
skill-security-scan scan skills/component-boundary-identifier -o _report/component-boundary-identifier
skill-security-scan scan skills/config-consistency-checker -o _report/config-consistency-checker
skill-security-scan scan skills/configuration-generator -o _report/configuration-generator
skill-security-scan scan skills/conflict-analyzer -o _report/conflict-analyzer
skill-security-scan scan skills/containerization-assistant -o _report/containerization-assistant
skill-security-scan scan skills/control-flow-abstraction-generator -o _report/control-flow-abstraction-generator
skill-security-scan scan skills/counterexample-debugger -o _report/counterexample-debugger
skill-security-scan scan skills/counterexample-explainer -o _report/counterexample-explainer
skill-security-scan scan skills/counterexample-generator -o _report/counterexample-generator
skill-security-scan scan skills/counterexample-to-test-generator -o _report/counterexample-to-test-generator
skill-security-scan scan skills/coverage-enhancer -o _report/coverage-enhancer
skill-security-scan scan skills/cpp-to-dafny-translator -o _report/cpp-to-dafny-translator
skill-security-scan scan skills/critical-interval-security-checker -o _report/critical-interval-security-checker
skill-security-scan scan skills/cve-reachability-analyzer -o _report/cve-reachability-analyzer
skill-security-scan scan skills/cve-watchlist-action-recommendation-generator -o _report/cve-watchlist-action-recommendation-generator
skill-security-scan scan skills/dead-code-eliminator -o _report/dead-code-eliminator
skill-security-scan scan skills/dependency-resolver -o _report/dependency-resolver
skill-security-scan scan skills/deprecated-api-updater -o _report/deprecated-api-updater
skill-security-scan scan skills/design-pattern-suggestor -o _report/design-pattern-suggestor
skill-security-scan scan skills/design-smell-detector -o _report/design-smell-detector
skill-security-scan scan skills/directed-test-input-generator -o _report/directed-test-input-generator
skill-security-scan scan skills/edge-case-generator -o _report/edge-case-generator
skill-security-scan scan skills/environment-setup-assistant -o _report/environment-setup-assistant
skill-security-scan scan skills/error-explanation-generator -o _report/error-explanation-generator
skill-security-scan scan skills/exploitability-analyzer -o _report/exploitability-analyzer
skill-security-scan scan skills/failure-oriented-instrumentation -o _report/failure-oriented-instrumentation
skill-security-scan scan skills/flaky-test-detector -o _report/flaky-test-detector
skill-security-scan scan skills/formal-spec-generator -o _report/formal-spec-generator
skill-security-scan scan skills/framework-migration-assistant -o _report/framework-migration-assistant
skill-security-scan scan skills/function-class-generator -o _report/function-class-generator
skill-security-scan scan skills/fuzzing-input-generator -o _report/fuzzing-input-generator
skill-security-scan scan skills/git-bisect-assistant -o _report/git-bisect-assistant
skill-security-scan scan skills/imperative-to-coq-model-extractor -o _report/imperative-to-coq-model-extractor
skill-security-scan scan skills/incremental-java-programmer -o _report/incremental-java-programmer
skill-security-scan scan skills/incremental-python-programmer -o _report/incremental-python-programmer
skill-security-scan scan skills/integration-test-generator -o _report/integration-test-generator
skill-security-scan scan skills/interface-contract-verifier -o _report/interface-contract-verifier
skill-security-scan scan skills/interface-specification-generator -o _report/interface-specification-generator
skill-security-scan scan skills/interval-difference-analyzer -o _report/interval-difference-analyzer
skill-security-scan scan skills/interval-guided-regression-test-update -o _report/interval-guided-regression-test-update
skill-security-scan scan skills/interval-profiling-performance-analyzer -o _report/interval-profiling-performance-analyzer
skill-security-scan scan skills/invariant-inference -o _report/invariant-inference
skill-security-scan scan skills/issue-report-generator -o _report/issue-report-generator
skill-security-scan scan skills/java-api-consistency-validator -o _report/java-api-consistency-validator
skill-security-scan scan skills/java-regression-test-generator -o _report/java-regression-test-generator
skill-security-scan scan skills/java-test-updater -o _report/java-test-updater
skill-security-scan scan skills/legacy-code-summarizer -o _report/legacy-code-summarizer
skill-security-scan scan skills/lemma-discovery-assistant -o _report/lemma-discovery-assistant
skill-security-scan scan skills/library-for-proof-advisor -o _report/library-for-proof-advisor
skill-security-scan scan skills/markdown-document-structurer -o _report/markdown-document-structurer
skill-security-scan scan skills/metamorphic-property-extractor -o _report/metamorphic-property-extractor
skill-security-scan scan skills/metamorphic-test-generator -o _report/metamorphic-test-generator
skill-security-scan scan skills/mocking-test-generator -o _report/mocking-test-generator
skill-security-scan scan skills/model-guided-code-repair -o _report/model-guided-code-repair
skill-security-scan scan skills/module-component-generator -o _report/module-component-generator
skill-security-scan scan skills/module-level-code-translator -o _report/module-level-code-translator
skill-security-scan scan skills/multi-version-behavior-comparator -o _report/multi-version-behavior-comparator
skill-security-scan scan skills/mutation-test-suite-optimizer -o _report/mutation-test-suite-optimizer
skill-security-scan scan skills/nl-to-constraints -o _report/nl-to-constraints
skill-security-scan scan skills/program-correctness-prover -o _report/program-correctness-prover
skill-security-scan scan skills/program-to-model-extractor -o _report/program-to-model-extractor
skill-security-scan scan skills/program-to-tlaplus-spec-generator -o _report/program-to-tlaplus-spec-generator
skill-security-scan scan skills/proof-carrying-code-generator -o _report/proof-carrying-code-generator
skill-security-scan scan skills/proof-failure-explainer -o _report/proof-failure-explainer
skill-security-scan scan skills/proof-refactoring-assistant -o _report/proof-refactoring-assistant
skill-security-scan scan skills/proof-skeleton-generator -o _report/proof-skeleton-generator
skill-security-scan scan skills/proof-trace-summarizer -o _report/proof-trace-summarizer
skill-security-scan scan skills/pseudocode-extractor -o _report/pseudocode-extractor
skill-security-scan scan skills/pseudocode-to-java-code -o _report/pseudocode-to-java-code
skill-security-scan scan skills/pseudocode-to-python-code -o _report/pseudocode-to-python-code
skill-security-scan scan skills/python-api-consistency-validator -o _report/python-api-consistency-validator
skill-security-scan scan skills/python-regression-test-generator -o _report/python-regression-test-generator
skill-security-scan scan skills/python-repo-quickstart -o _report/python-repo-quickstart
skill-security-scan scan skills/python-test-updater -o _report/python-test-updater
skill-security-scan scan skills/python-to-dafny-translator -o _report/python-to-dafny-translator
skill-security-scan scan skills/python-to-lean4-translator -o _report/python-to-lean4-translator
skill-security-scan scan skills/readme-generator -o _report/readme-generator
skill-security-scan scan skills/refinement-step-generator -o _report/refinement-step-generator
skill-security-scan scan skills/regression-consistency-checker -o _report/regression-consistency-checker
skill-security-scan scan skills/regression-root-cause-analyzer -o _report/regression-root-cause-analyzer
skill-security-scan scan skills/release-notes-writer -o _report/release-notes-writer
skill-security-scan scan skills/replay-oriented-instrumentation -o _report/replay-oriented-instrumentation
skill-security-scan scan skills/reproduction-trace-instrumenter -o _report/reproduction-trace-instrumenter
skill-security-scan scan skills/req-to-test -o _report/req-to-test
skill-security-scan scan skills/requirement-comparison-reporter -o _report/requirement-comparison-reporter
skill-security-scan scan skills/requirement-coverage-checker -o _report/requirement-coverage-checker
skill-security-scan scan skills/requirement-enhancer -o _report/requirement-enhancer
skill-security-scan scan skills/requirement-summarizer -o _report/requirement-summarizer
skill-security-scan scan skills/requirement-summary -o _report/requirement-summary
skill-security-scan scan skills/requirement-to-tlaplus-property-generator -o _report/requirement-to-tlaplus-property-generator
skill-security-scan scan skills/rollback-strategy-advisor -o _report/rollback-strategy-advisor
skill-security-scan scan skills/rtl-equivalence-checker -o _report/rtl-equivalence-checker
skill-security-scan scan skills/rtl-property-inference -o _report/rtl-property-inference
skill-security-scan scan skills/rtl-specification-consistency-checker -o _report/rtl-specification-consistency-checker
skill-security-scan scan skills/runtime-error-explainer -o _report/runtime-error-explainer
skill-security-scan scan skills/scenario-generator -o _report/scenario-generator
skill-security-scan scan skills/security-patch-advisor -o _report/security-patch-advisor
skill-security-scan scan skills/security-sensitive-path-instrumenter -o _report/security-sensitive-path-instrumenter
skill-security-scan scan skills/semantic-bug-detector -o _report/semantic-bug-detector
skill-security-scan scan skills/semantic-equivalence-verifier -o _report/semantic-equivalence-verifier
skill-security-scan scan skills/semantic-szz-analyzer -o _report/semantic-szz-analyzer
skill-security-scan scan skills/skill-creator -o _report/skill-creator
skill-security-scan scan skills/smart-mutation-operator-generator -o _report/smart-mutation-operator-generator
skill-security-scan scan skills/smv-model-extractor -o _report/smv-model-extractor
skill-security-scan scan skills/specification-driven-generation -o _report/specification-driven-generation
skill-security-scan scan skills/specification-generator -o _report/specification-generator
skill-security-scan scan skills/specification-to-temporal-logic-generator -o _report/specification-to-temporal-logic-generator
skill-security-scan scan skills/spring-mvc-to-boot-migrator -o _report/spring-mvc-to-boot-migrator
skill-security-scan scan skills/state-snapshot-instrumenter -o _report/state-snapshot-instrumenter
skill-security-scan scan skills/static-bug-detector -o _report/static-bug-detector
skill-security-scan scan skills/static-reasoning-verifier -o _report/static-reasoning-verifier
skill-security-scan scan skills/static-vulnerability-detector -o _report/static-vulnerability-detector
skill-security-scan scan skills/symbolic-execution-assistant -o _report/symbolic-execution-assistant
skill-security-scan scan skills/system-diagram-generator -o _report/system-diagram-generator
skill-security-scan scan skills/szz-bug-identifier -o _report/szz-bug-identifier
skill-security-scan scan skills/tactic-suggestion-assistant -o _report/tactic-suggestion-assistant
skill-security-scan scan skills/taint-instrumentation-assistant -o _report/taint-instrumentation-assistant
skill-security-scan scan skills/technical-debt-analyzer -o _report/technical-debt-analyzer
skill-security-scan scan skills/template-code-generator -o _report/template-code-generator
skill-security-scan scan skills/test-case-documentation -o _report/test-case-documentation
skill-security-scan scan skills/test-case-reducer -o _report/test-case-reducer
skill-security-scan scan skills/test-deduplicator -o _report/test-deduplicator
skill-security-scan scan skills/test-driven-generation -o _report/test-driven-generation
skill-security-scan scan skills/test-guided-bug-detector -o _report/test-guided-bug-detector
skill-security-scan scan skills/test-guided-debloating -o _report/test-guided-debloating
skill-security-scan scan skills/test-guided-migration-assistant -o _report/test-guided-migration-assistant
skill-security-scan scan skills/test-oracle-generator -o _report/test-oracle-generator
skill-security-scan scan skills/test-suite-prioritizer -o _report/test-suite-prioritizer
skill-security-scan scan skills/time-aware-dependency-cve-scanner -o _report/time-aware-dependency-cve-scanner
skill-security-scan scan skills/tlaplus-guided-code-repair -o _report/tlaplus-guided-code-repair
skill-security-scan scan skills/tlaplus-model-reduction -o _report/tlaplus-model-reduction
skill-security-scan scan skills/tlaplus-spec-generator -o _report/tlaplus-spec-generator
skill-security-scan scan skills/trace-collection-assistant -o _report/trace-collection-assistant
skill-security-scan scan skills/traceability-matrix-generator -o _report/traceability-matrix-generator
skill-security-scan scan skills/unit-test-generator -o _report/unit-test-generator
skill-security-scan scan skills/verification-boundary-reporter -o _report/verification-boundary-reporter
skill-security-scan scan skills/verified-pseudocode-extractor -o _report/verified-pseudocode-extractor
skill-security-scan scan skills/verified-spec-code-mapper -o _report/verified-spec-code-mapper
skill-security-scan scan skills/vulnerability-pattern-matcher -o _report/vulnerability-pattern-matcher
skill-security-scan scan skills/vulnerability-root-cause-analyzer -o _report/vulnerability-root-cause-analyzer
